### ISSUE TITLE
2025 지방 기능경기대회 예상

### ISSUE THREAD

**Issue by halo0015** [halo0015/-#2]
### **1. AWS Management Console을 사용하여 ECR 레포지토리 생성**

1. **AWS 콘솔에 로그인**
    - [[AWS ECR 콘솔](https://console.aws.amazon.com/ecr)](https://console.aws.amazon.com/ecr) 로 이동
2. **레포지토리 생성하기**
    - **왼쪽 메뉴에서 "리포지토리" 클릭**
    - **"리포지토리 생성" 버튼 클릭**
    - **설정 입력**
        - **리포지토리 이름:**
            - `user`
            - `token`
        - **암호화:**
            - "AWS 관리형 KMS 키" 선택 (기본 설정)
        - **이미지 태그 변경 가능 여부:**
            - "변경 불가능(Immutable)" 선택 (태그 중복 방지)
        - **푸시 시 스캔 활성화:**
            - "예" 선택 (취약점 분석 활성화)
    - **"리포지토리 생성" 클릭**

---

### **2. AWS CLI를 사용하여 생성**

터미널에서 AWS CLI를 사용해 직접 생성할 수도 있어요.

### **1) user 레포지토리 생성**

```
sh
복사편집
aws ecr create-repository --repository-name user \
  --image-tag-mutability IMMUTABLE \
  --encryption-configuration encryptionType=KMS \
  --image-scanning-configuration scanOnPush=true

```

### **2) token 레포지토리 생성**

```
sh
복사편집
aws ecr create-repository --repository-name token \
  --image-tag-mutability IMMUTABLE \
  --encryption-configuration encryptionType=KMS \
  --image-scanning-configuration scanOnPush=true

```

---

### **3. 생성된 레포지토리 확인**

```
sh
복사편집
aws ecr describe-repositories --repository-names user token

```

이제 **user**와 **token** 레포지토리가 정상적으로 생성되었는지 확인할 수 있습니다! 🚀

### 나의 말:

제공자료로 주어진 애플리케이션은 Golang으로 개발된 바이너리입니다. token 바이너리는 x86_64 기반에서 빌드되었으며, user 바이너리는 ARM64 기반에서 빌드되었습니다. user 애플리케이션은 token 애플리케이션의 REST API 사용이 가능해야 합니다. 부록 2에 명시된 바이너리 사용 방법을 충분히 숙지하고, 애플리케이션을 운용해야 합니다. 또한, 컨테이너 이미지 내에서 curl 사용이 가능해야 합니다. 제공자료에 API 문서가 있습니다.

### ChatGPT의 말:

주어진 조건을 만족하는 컨테이너 이미지를 빌드하고 AWS ECR에 업로드하는 과정을 설명드릴게요.

---

## **1. 요구 사항 정리**

- **Golang 바이너리 실행 가능하도록 컨테이너 이미지 구성**
- `user` (ARM64) → `token` (x86_64) REST API 호출 가능
- `curl` 설치 필수
- 제공된 API 문서 참고하여 애플리케이션 운용

---

## **2. Dockerfile 작성**

각 애플리케이션에 맞는 Dockerfile을 생성해야 합니다.

### **(1) token 컨테이너 (x86_64 기반)**

```
dockerfile
복사편집
# 선택적: 멀티스테이지 빌드를 사용하려면 Golang 빌드 단계 추가 가능
FROM alpine:latest

# curl 설치
RUN apk add --no-cache curl

# 제공된 token 바이너리 복사
COPY token /usr/local/bin/token

# 실행 권한 부여
RUN chmod +x /usr/local/bin/token

# 실행
CMD ["/usr/local/bin/token"]

```

---

### **(2) user 컨테이너 (ARM64 기반)**

```
dockerfile
복사편집
FROM alpine:latest

# curl 설치
RUN apk add --no-cache curl

# 제공된 user 바이너리 복사
COPY user /usr/local/bin/user

# 실행 권한 부여
RUN chmod +x /usr/local/bin/user

# 실행
CMD ["/usr/local/bin/user"]

```

---

### **token 이미지 빌드 (x86_64)**

```
sh
복사편집
docker build -t token-app --platform=linux/amd64 -f Dockerfile.token .

```

### **user 이미지 빌드 (ARM64)**

```
sh
복사편집
docker build -t user-app --platform=linux/arm64 -f Dockerfile.user .

```

---

## **4. AWS ECR에 업로드**

1. **ECR 로그인**

```
sh
복사편집
aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com

```

1. **ECR 리포지토리 생성 (이미 생성했다면 건너뛰기)**

```
sh
복사편집
aws ecr create-repository --repository-name user
aws ecr create-repository --repository-name token

```

1. **이미지 태그 설정 및 푸시**

```
sh
복사편집
docker tag token-app <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest
docker tag user-app <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/user:latest

docker push <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest
docker push <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/user:latest

```

---

## **5. user 컨테이너에서 token 컨테이너의 API 호출**

`user` 애플리케이션이 `token` API를 호출할 수 있도록 환경 변수 또는 설정을 통해 `token` 컨테이너의 주소를 전달해야 합니다.

예제:

```
sh
복사편집
curl -X GET http://token-container:8080/api/status

```

---

이제 `user`와 `token` 애플리케이션을 컨테이너로 실행하고 AWS ECR을 통해 배포할 수 있습니다! 🚀

### 나의 말:

dockerfile에서 token 컨테이너와 user컨테이너는 하나 하나식 user 컨테이너를 ec2생성해야 해?

### ChatGPT의 말:

아니요! **EC2 인스턴스를 각각 생성할 필요 없이**, 하나의 EC2에서 **두 개의 컨테이너(token, user)** 를 실행할 수 있습니다.

방법은 두 가지입니다.

1. **Docker Compose 사용** (추천)
2. **개별 Docker 컨테이너 실행**

---

## **1. Docker Compose 사용 (추천)**

Docker Compose를 사용하면 **한 번의 명령어**로 `user`와 `token` 컨테이너를 실행할 수 있습니다.

### **(1) `docker-compose.yml` 파일 생성**

EC2 인스턴스에서 다음 파일을 작성하세요.

```yaml
yaml
복사편집
version: '3'
services:
  token:
    image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest
    platform: linux/amd64
    container_name: token-container
    ports:
      - "8080:8080"  # token 서비스가 8080 포트에서 실행됨
  user:
    image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/user:latest
    platform: linux/arm64
    container_name: user-container
    depends_on:
      - token  # user 컨테이너는 token 컨테이너가 실행된 후 시작됨
    environment:
      TOKEN_API_URL: "http://token-container:8080"
    ports:
      - "8081:8081"  # user 서비스가 8081 포트에서 실행됨

```

### **(2) 실행 방법**

```
sh
복사편집
docker-compose up -d

```

이제 **하나의 EC2에서 `user`와 `token` 컨테이너가 동시에 실행**됩니다.

---

## **2. 개별 컨테이너 실행 (수동 방법)**

Docker Compose 없이 개별적으로 실행할 수도 있습니다.

### **(1) `token` 컨테이너 실행**

```
sh
복사편집
docker run -d --name token-container -p 8080:8080 <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest

```

### **(2) `user` 컨테이너 실행**

```
sh
복사편집
docker run -d --name user-container -p 8081:8081 -e TOKEN_API_URL="http://token-container:8080" <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/user:latest

```

이렇게 하면 **user 컨테이너가 token 컨테이너의 API를 사용할 수 있습니다.**

하지만 이 방법은 `docker-compose`보다 관리가 어려울 수 있습니다.

---

## **결론**

✅ **가장 쉬운 방법:** `docker-compose.yml`을 사용해 한 번에 실행

✅ **수동 방법:** `docker run`을 이용해 각각 실행

🎯 **EC2를 하나만 생성하고, 그 위에서 두 개의 컨테이너를 실행하면 됩니다.** 🚀
