### ISSUE TITLE
docker arm64, x86_64 컨테이너 차이

### ISSUE THREAD

**Issue by halo0015** [halo0015/-#3]
### **1. Docker 빌드 시 아키텍처 설정**

Docker에서 `--platform` 옵션을 사용하면 특정 아키텍처의 이미지를 생성할 수 있습니다.

### **(1) `token` 컨테이너 (x86_64 기반) 빌드**

```
sh
복사편집
docker build --platform=linux/amd64 -t token-app -f Dockerfile.token .

```

### **(2) `user` 컨테이너 (ARM64 기반) 빌드**

```
sh
복사편집
docker build --platform=linux/arm64 -t user-app -f Dockerfile.user .

```

💡 **멀티 아키텍처 빌드 지원이 필요하다면, `buildx` 사용 추천**

```
sh
복사편집
docker buildx create --use
docker buildx build --platform linux/arm64 -t user-app -f Dockerfile.user .

```

---

### **2. AWS ECR에 올릴 때 태그 설정**

```
sh
복사편집
docker tag token-app <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest
docker tag user-app <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/user:latest

docker push <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest
docker push <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/user:latest

```

---

### **3. 컨테이너 실행 시 아키텍처 확인**

ECR에서 가져온 이미지를 실행할 때, 아키텍처를 명확히 지정하려면 `--platform` 옵션을 사용하세요.

### **(1) `token` 컨테이너 (x86_64 기반) 실행**

```
sh
복사편집
docker run --platform=linux/amd64 -d --name token-container -p 8080:8080 <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest

```

### **(2) `user` 컨테이너 (ARM64 기반) 실행**

```
sh
복사편집
docker run --platform=linux/arm64 -d --name user-container -p 8081:8081 -e TOKEN_API_URL="http://token-container:8080" <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/user:latest

```

---

### **4. Docker Compose에서 아키텍처 설정**

Docker Compose에서도 `platform`을 지정하여 실행할 수 있습니다.

```yaml
yaml
복사편집
version: '3'
services:
  token:
    image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest
    platform: linux/amd64  # x86_64 기반 실행
    container_name: token-container
    ports:
      - "8080:8080"
  user:
    image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/user:latest
    platform: linux/arm64  # ARM64 기반 실행
    container_name: user-container
    depends_on:
      - token
    environment:
      TOKEN_API_URL: "http://token-container:8080"
    ports:
      - "8081:8081"

```

실행 명령어:

```
sh
복사편집
docker-compose up -d

```

---

### **5. 현재 실행 중인 컨테이너 아키텍처 확인**

컨테이너 내부에서 아키텍처 확인:

```
sh
복사편집
docker exec -it token-container uname -m
docker exec -it user-container uname -m

```

- `x86_64`가 출력되면 `amd64` 기반
- `aarch64`가 출력되면 `arm64` 기반

---

## **결론**

1. **이미지 빌드 시 `-platform` 사용**
2. **ECR 업로드 후 실행 시 `-platform` 사용**
3. **Docker Compose 사용 시 `platform` 설정 가능**
4. **컨테이너 내부에서 `uname -m`으로 확인 가능**

이제 `user`는 `arm64`로, `token`은 `x86_64`로 올바르게 실행할 수 있습니다! 🚀
